FROM node:22-alpine AS build


# Step 2: Set working directory
WORKDIR /app

# Step 3: Copy package.json and package-lock.json
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the app
COPY . .

# Step 6: Build the React (Vite) app
RUN npm run build

# Step 7: Use Nginx to serve the built files
FROM nginx:stable-alpine

# Step 8: Copy build output to Nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html

# Step 9: Expose port 80
EXPOSE 80

# Step 10: Start Nginx
CMD ["nginx", "-g", "daemon off;"]
